In [2]:
import pandas as pd
import numpy as np
games = pd.read_csv("C:/Users/user/Desktop/game dataset/games.csv")

In [11]:
# calculate cosine similarity

def cos_sim(x, y):
    numerator = np.dot(x, y)
    denominator = np.linalg.norm(x) * np.linalg.norm(y)
    return numerator / denominator


games.head()

,app_id,date_release,win,mac,linux,rating,positive_ratio,user_reviews,price_final,price_original,discount,steam_deck
3,226560,2014-11-18,True,False,False,Mixed,61,873,14.99,14.99,0.0,True
4,249050,2014-10-27,True,True,False,Very Positive,88,8784,11.99,11.99,0.0,True
5,250180,2015-09-14,True,False,False,Very Positive,90,5579,7.99,7.99,0.0,True
6,253980,2013-10-04,True,True,True,Mostly Positive,75,1608,4.99,4.99,0.0,True
7,271850,2014-05-16,True,False,False,Mixed,61,199,6.99,6.99,0.0,True

In [16]:
games_preprocessed = pd.read_csv('games_preprocessing.csv')
games_preprocessed = games_preprocessed.drop("title", axis=1)
games_preprocessed.head()

,Unnamed: 0,app_id,date_release,win,mac,linux,rating,positive_ratio,user_reviews,price_final,price_original,discount,steam_deck
0,15005,282010,1997,1,0,0,90,85,428,9.99,9.99,0.0,1
1,31261,232770,1997,1,1,1,90,85,2329,0.00,0.00,0.0,1
2,47376,70,1998,1,1,1,95,96,72475,9.99,9.99,0.0,1
3,34507,224920,1999,1,0,0,80,73,1467,0.00,0.00,0.0,1
4,8617,20,1999,1,1,1,90,85,5146,4.99,4.99,0.0,1

In [17]:
item_sim = games_preprocessed.dot(games_preprocessed.T) / np.linalg.norm(games_preprocessed, axis=1)

In [23]:
print(item_sim)

              0             1             2             3             4
0      2.824163e+05  2.814951e+05   8840.229265  2.810276e+05  13791.359359  \
1      2.341137e+05  2.348799e+05  19283.390867  2.348372e+05  28337.750062
2      2.711047e+03  7.110512e+03  86609.043117  7.737905e+03  76721.342478
3      2.264462e+05  2.275239e+05  20331.334993  2.275652e+05  30622.172098
4      4.997877e+02  1.234775e+03   9066.115147  1.377205e+03  10234.538817
...             ...           ...           ...           ...           ...
50867  2.354859e+06  2.340753e+06  27021.611353  2.335382e+06  43579.285968
50868  1.140837e+06  1.134179e+06  14312.076515  1.131618e+06  23149.347639
50869  1.961438e+06  1.950383e+06  27248.461045  1.946070e+06  43638.511083
50870  1.668393e+06  1.659558e+06  27262.110462  1.656020e+06  43238.319137
50871  2.487647e+06  2.472946e+06  30005.591754  2.467317e+06  48163.011423

              5             6             7             8             9
0      10182.336728   5383.294853  15910.834670  13967.622514  16113.328104  \
1      21106.582121  12517.964434  31931.851555  26890.272919  31795.328390
2      86126.494898  84040.189455  60752.526166  83109.274838  59821.699018
3      22298.509412  12770.279966  34890.930891  28670.181702  34693.926732
4       9411.054826   7719.605176   9643.153516  10035.613129   9679.558553
...             ...           ...           ...           ...           ...
50867  33846.464498  15260.721671  53099.819770  53431.202608  54666.616739
50868  17799.350716   8132.408069  27960.408412  27634.495400  28790.367150
50869  33306.953898  15566.784103  52667.092862  50962.947432  53855.403028
50870  32713.289619  15816.800748  51731.631806  48788.782435  52648.905397
50871  37298.826122  17056.696361  58513.102816  58352.294729  60112.232810

       ...         50862         50863         50864         50865
0      ...  2.822564e+05  2.822564e+05  2.823006e+05  2.822735e+05  \
1      ...  2.333534e+05  2.333535e+05  2.334858e+05  2.334030e+05
2      ...  1.028645e+03  1.025687e+03  1.266376e+03  1.117292e+03
3      ...  2.255703e+05  2.255704e+05  2.257200e+05  2.256262e+05
4      ...  1.953387e+02  1.951522e+02  2.393477e+02  2.116289e+02
...    ...           ...           ...           ...           ...
50867  ...  2.356246e+06  2.356246e+06  2.356207e+06  2.356239e+06
50868  ...  1.141431e+06  1.141431e+06  1.141423e+06  1.141431e+06
50869  ...  1.962305e+06  1.962305e+06  1.962317e+06  1.962316e+06
50870  ...  1.668896e+06  1.668896e+06  1.668942e+06  1.668918e+06
50871  ...  2.489031e+06  2.489031e+06  2.489002e+06  2.489028e+06

              50866         50867         50868         50869         50870
0      2.822548e+05  2.822501e+05  2.822692e+05  2.822895e+05  2.823223e+05  \
1      2.333488e+05  2.333355e+05  2.333875e+05  2.334512e+05  2.335583e+05
2      1.016882e+03  9.932391e+02  1.085965e+03  1.202640e+03  1.414750e+03
3      2.255650e+05  2.255501e+05  2.256086e+05  2.256808e+05  2.258023e+05
4      1.935899e+02  1.892900e+02  2.075664e+02  2.275981e+02  2.651515e+02
...             ...           ...           ...           ...           ...
50867  2.356246e+06  2.356246e+06  2.356241e+06  2.356223e+06  2.356159e+06
50868  1.141430e+06  1.141429e+06  1.141432e+06  1.141428e+06  1.141406e+06
50869  1.962304e+06  1.962300e+06  1.962312e+06  1.962319e+06  1.962301e+06
50870  1.668893e+06  1.668886e+06  1.668911e+06  1.668934e+06  1.668949e+06
50871  2.489030e+06  2.489029e+06  2.489029e+06  2.489016e+06  2.488958e+06

              50871
0      2.822593e+05
1      2.333620e+05
2      1.044083e+03
3      2.255799e+05
4      1.980394e+02
...             ...
50867  2.356245e+06
50868  1.141431e+06
50869  1.962308e+06
50870  1.668900e+06
50871  2.489031e+06

[50872 rows x 50872 columns]